name: comment
on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - name: generate value
        id: value-generator
        run: echo "BUILD_SIZE=1564" >> "$GITHUB_OUTPUT"

      - name: post comment
        uses: actions/github-script@v6
        with:
          script: |
            console.log("here you are:", ${{ steps.value-generator.outputs.BUILD_SIZE }});
            const response = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const comments = response.data;
            previousComments = comments.filter(comment => {
              return comment.body.includes('[Test bot]');
            });

            // remove previous comments left by this bot
            previousComments.forEach(comment => {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
              })
            });

            // create comment
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "[Test bot]: some text here"
            })
