name: publish-new-version
on:
  workflow_dispatch:
    inputs:
      update_type:
        description: What type of version you want to publish?
        options:
          - patch
          - minor
          - major

jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ github.event.inputs.update_type }}"
      - run: date > date.txt 
      - run: git status
      - run: git add .
      - run: git config user.email test@test.com
      - run: git config user.name github-actions
      - run: git commit -m "github-action"
      - run: git push

