name: publish-new-version
on: [push]
jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: date > date.txt 
      - run: git status
      - run: git add .
      - run: git config user.email test@test.com
      - run: git config user.name github-actions
      - run: git commit -m "github-action"
      - run: git push

