name: publish-new-version
on: [push]
jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Test echo successfull"
      - run: ls -a
      - run: git log
      - run: git remote -v

